def throw_exception():
    pass
